[package]
name = "momochi_tool_watcher"
version = "0.1.0"
authors = ["Martin Pernica"]

[dependencies]
clap = "~2.19.0"
log = "^0.3.8"
simplelog = "^0.4.2"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0.2"
